export { IStudentAboutData } from './Student/Student.type'
export { IAboutGroupData } from './Student/Student.type'
export { IOnlyStudentsInGroupData } from './Student/Student.type'
export { IColumnNames } from './Student/Student.type'
export { IStudentData } from './Student/Student.type'
