# Generated by Django 4.2.1 on 2023-07-15 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_course_student'),
        ('file_tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetasksanswer',
            name='list_modules',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules'),
        ),
        migrations.AddField(
            model_name='filetasksanswer',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetasks',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
