# Generated by Django 4.2.1 on 2023-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
