# Generated by Django 4.2.1 on 2023-08-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0011_listmodules_course'),
        ('file_tasks', '0003_filetasks_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetasksanswer',
            name='file_task',
        ),
        migrations.AlterField(
            model_name='filetasksanswer',
            name='list_modules',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules'),
        ),
    ]
