# Generated by Django 4.2.1 on 2023-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0005_alter_filetasksanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetasksanswer',
            name='module_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
