# Generated by Django 4.2.1 on 2023-08-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_tasks', '0007_filetasksanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetasksanswer',
            old_name='answer',
            new_name='description',
        ),
    ]
