# Generated by Django 4.2.1 on 2023-07-15 16:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_course_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(null=True)),
                ('correct_answer', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('options', models.ManyToManyField(blank=True, to='test_tasks.testansweroptions')),
            ],
        ),
        migrations.CreateModel(
            name='TestTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_minute', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('questions', models.ManyToManyField(blank=True, to='test_tasks.testquestionanswer')),
            ],
        ),
        migrations.CreateModel(
            name='TestGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data', models.DateTimeField(auto_now=True)),
                ('is_late', models.BooleanField(blank=True, default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('list_modules', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_tasks.testtasks')),
            ],
        ),
    ]
