# Generated by Django 4.2.1 on 2023-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_student'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(through='teachers.CourseTeacher', to='teachers.teachers'),
        ),
    ]
