# Generated by Django 4.2.1 on 2023-08-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_remove_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
