# Generated by Django 4.2.1 on 2023-06-23 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admins',
            name='patronymic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admins',
            name='surname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admins',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
