# Generated by Django 4.2.1 on 2023-07-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_course_student'),
        ('lectures', '0001_initial'),
        ('file_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('module_type', models.CharField(choices=[('1', 'lecture'), ('2', 'test task'), ('3', 'file task')], default='1', max_length=1)),
                ('number', models.IntegerField(blank=True, default=1)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('file_task_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_tasks.filetasks')),
                ('lecture_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.lectures')),
            ],
        ),
    ]
