# Generated by Django 4.2.1 on 2023-07-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_tasks', '0001_initial'),
        ('list_modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodules',
            name='test_task_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_tasks.testtasks'),
        ),
    ]
