# Generated by Django 4.2.1 on 2023-07-22 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_price'),
        ('list_modules', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(blank=True, default=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('list_module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules')),
            ],
        ),
    ]
