# Generated by Django 4.2.1 on 2023-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0004_remove_modules_list_module_modules_list_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='list_module',
            field=models.ManyToManyField(blank=True, to='list_modules.listmodules'),
        ),
    ]
