# Generated by Django 4.2.1 on 2023-07-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0006_remove_listmodules_course_remove_listmodules_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='list_module',
        ),
        migrations.AddField(
            model_name='listmodules',
            name='module',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listmodules',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
