# Generated by Django 4.2.1 on 2023-07-22 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0007_remove_modules_list_module_listmodules_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodules',
            name='module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_module', to='list_modules.listmodules'),
        ),
    ]
