# Generated by Django 4.2.1 on 2023-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0009_remove_listmodules_module_modules_list_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
