# Generated by Django 4.2.1 on 2023-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='files/')),
            ],
        ),
    ]
