# Generated by Django 4.2.1 on 2023-07-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='list_modules',
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
