# Generated by Django 4.2.1 on 2023-07-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_modules', '0010_alter_modules_description'),
        ('grades', '0003_remove_grades_list_modules_alter_grades_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='list_modules',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list_modules.listmodules'),
            preserve_default=False,
        ),
    ]
