# Generated by Django 4.2.1 on 2023-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_grades_list_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='module_index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
