# Generated by Django 4.2.1 on 2023-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='additions',
            field=models.ManyToManyField(blank=True, null=True, to='lectures.additions'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, to='lectures.lessoncontent'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
