# Generated by Django 4.2.1 on 2023-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_additions_file_alter_lectures_additions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectures',
            old_name='content',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='additions',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
