# Generated by Django 4.2.1 on 2023-07-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_rename_content_lectures_lesson_alter_additions_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='course',
        ),
    ]
