# Generated by Django 4.2.1 on 2023-07-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_price'),
        ('lectures', '0004_remove_lectures_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
