# Generated by Django 4.2.1 on 2023-07-15 13:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('country', models.CharField(max_length=80, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=40, null=True)),
                ('surname', models.CharField(max_length=40, null=True)),
                ('patronymic', models.CharField(max_length=40, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('university', models.CharField(max_length=80, null=True)),
                ('courses', models.ManyToManyField(through='students.CourseStudent', to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
