# Generated by Django 4.2.1 on 2023-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
