# Generated by Django 4.2.1 on 2023-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_students_avatar_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
